version: '3.9'

services:
  productos:
    build: ./productos
    container_name: productos
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVICES_API_KEY=123456789
    volumes:
      - productos-data:/app/data

  inventario:
    build: ./inventario
    container_name: inventario
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVICES_API_KEY=123456789   # Coincide con @Value("${services.api-key}")
      - PRODUCTOS_SERVICE_URL=http://productos:8080  # Coincide con @Value("${productos.service.url}")
    depends_on:
      - productos
    volumes:
      - inventario-data:/app/data

volumes:
  productos-data:
  inventario-data:
